user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Homepage:home }

user_registration:
    path:     /register
    defaults: { _controller: UserBundle:Registration:register }


login:
    path:     /login
    defaults: { _controller: UserBundle:Security:login }

logout:
    path: /logout
