<?php

namespace EntityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * YoutubeVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YoutubeVideoRepository extends EntityRepository
{
}
