video_upload:
    path: /upload
    defaults: { _controller: VideoBundle:Upload:video}

video_show:
    path:     /video/show/{video_Id}
    defaults: { _controller: VideoBundle:ShowVideo:show}

video_custom_upload:
    path: /customupload
    defaults: { _controller: VideoBundle:CustomUpload:customUpload}