EntityBundle\Entity\DesktopVideo:
    type: entity
    table: null
    repositoryClass: EntityBundle\Repository\DesktopVideoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        title:
            type: string
            length: 30

        description:
            type: string
            length: 400

        videoFile :
             - File:
                   maxSize: 6000000000000
        videoName :
            type : string
            length : 255

        previewFile :
             - File:
                   maxSize: 6000000000000
        previewImageName :
            type : string
            length : 255

    manyToOne:
        user:
            targetEntity: EntityBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
